autocmd FileType c setlocal expandtab
autocmd FileType c setlocal shiftwidth=2
autocmd FileType c setlocal softtabstop=2
autocmd FileType cpp setlocal expandtab
autocmd FileType cpp setlocal shiftwidth=2
autocmd FileType cpp setlocal softtabstop=2
autocmd FileType sh setlocal expandtab
autocmd FileType sh setlocal shiftwidth=2
autocmd FileType sh setlocal softtabstop=2
